### ISSUE TITLE
RxJS-TestScheduler-Injector should be published as an NPM module

### ISSUE THREAD

**Issue by HipsterZipster** [tchock/RxJS-TestScheduler-Injector#2]
Title is pretty self-explanatory. I'm happy to lend a hand with this, but we'd need to decide on a namespace and account ownership. Let me know how you'd like to approach this.

**Comment by mattcompiles** [comment]
+1

**Comment by tchock** [comment]
I will definitely do this. I maybe have some time at the end of the week

**Comment by tchock** [comment]
I will definitely do this. I maybe have some time at the end of the week

@HipsterZipster we should definitely use something rxjs 4 related for the namespace so there can be a rxjs 5+ version in the future. I think I will use Browserify for ongoing Bower support.

**Comment by tchock** [comment]
updated the package to work as a npm package. Package name is "rx-jasmine-testscheduler-injector" (see the README). Bower support is still there through browserified version.

The npm package works with RxJs 4.
